package id.ac.poliban.mi.aulia.listpahlawan;

import java.util.ArrayList;
import java.util.List;

public class HeroData {
    static List<Hero> getAllHero() {
        List<Hero> data = new ArrayList<>();
        data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/3/3f/Ahmad_Yani.jpg", "Jenderal TNI Anumerta Ahmad Yani", "Beliau merupakan komandan TNI AD yang lahir pada tahun 19 Juni 1922 di Purworejo. Pembantaian terhadapnya disebabkan beliau sangat menentang keberadaan faham komunis di tanah air.Kemudian beliau diculik dari tempat tinggalnya lalu dibantai di Lubang Buaya."));
        data.add(new Hero("http://1.bp.blogspot.com/-a0gYgMqLRFY/VfL8VlaYg1I/AAAAAAAAAJg/z1o7r6yssYI/s1600/R.Suprapto.jpg", "Letnan Jenderal Anumerta Suprapto", "Letnan Jenderal Anumerta Suprapto adalah salah satu pahlawan nasional yang lahir di Purwokerto, 20 Juni 1920. Beliau juga diculik dari rumahnya dan dibantai di Lubang Buaya.Sebelum akhirnya tewas di tangan PKI, beliau pernah meredam beberapa pemberontakan PKI di berbagai wilayah seperti Semarang dan Medan."));
        data.add(new Hero("https://pahlawancenter.com/wp-content/uploads/2013/09/Letjen-MT-Haryono-bw-253x300.jpg", "Letnan Jenderal Haryono", "Letnan Jenderal TNI Anumerta atau Mas Tirtodarmo Haryono (MT Haryono) lahir di Surabaya, 20 Januari 1924.Letjend yang mengerti 3 bahasa asing ini juga diculik pada saat hari kejadian.Kemudian dibantai di Lubang Buaya."));
        data.add(new Hero("https://pahlawancenter.com/wp-content/uploads/2013/09/Letjen-S-Parman-bw-253x300.jpg", "Letnan Jenderal Siswondo Parman", "Siswondo Parman atau lebih dikenal dengan nama S. Parman adalah salah satu pahlawan revolusi Indonesia dan tokoh militer Indonesia.Lahir di Wonosobo, 4 Agustus 1918.Beliau merupakan perwira intelijen yang dekat dengan PKI serta mengetahui kegiatan rahasia mereka.Namun saat ditawari bergabung dengan faham komunis, S Parman menolak.Karena itulah beliau meninggal dibunuh pada persitiwa Gerakan 30 September dan mendapatkan gelar Letnan Jenderal Anumerta.Otak pembantaiannya yakni kakaknya sendiri Ir. Sakirman yang merupakan petinggi PKI saat itu."));
        data.add(new Hero("https://pahlawancenter.com/wp-content/uploads/2013/09/DI-Pandjaitan-bw-253x300.jpg", "Mayor Jenderal Pandjaitan", "Brigadir Jenderal TNI Anumerta Donald Isaac Panjaitan lahir di Sumatera Utara, 19 Juni 1925. Beliau dan bersama para pemuda anak bangsa lain yang dulunya merintis pembentukan Tentara Keamanan Rakyat (TKR) yang merupakan cikal bakal TNI saat ini. Saat itu beliau menggunakan seragam militer lengkap ketika tahu bahwa sekelompok anggota OKI datang ke rumahnya dan telah membunuh pelayan serta ajudannya. Segera setelah beliau menantang para pemberontak itu, peluru langsung menghujam tubuhnya dan mayatnya dibawa ke Lubang Buaya."));
        data.add(new Hero("https://pahlawancenter.com/wp-content/uploads/2013/09/Mayjen-Soetojo-Siswomihardjo-bw-253x300.jpg", "Mayor Jenderal Sutoyo Siswomiharjo", "Mayor Jenderal TNI Anumerta Sutoyo Siswomiharjo lahir di Kebumen, 23 Agustus 1922. Beliaujuga diculik di rumahnya dan dibantai di Lubang Buaya. Para penculik mengatakan Mayjen Sutoyo dipanggil oleh Presiden Republik Indonesia pertama Ir. Soekarno, tapi ternyata itu bohong."));
        data.add(new Hero("https://pahlawancenter.com/wp-content/uploads/2013/09/Pierre-Tendean-bw-253x300.jpg", "Kapten Pierre Tendean","Kapten CZI Anumerta Pierre Andreas Tendean lahir 21 Februari 1939. Meninggalnya masih sangat terlalu muda, yakni umur 26 tahun. Beliau merupakan pahlawan revolusi satu-satunya yang tak berpangkat jenderal namun memiliki keberanian yang membara. Berkat keberaniannya, atasan beliau dapat lolos dengan mengakui diri sebagai A.H. Nasution. Kapten Pierre Tendean dibunuh lalu dibantai di Lubang Buaya."));
        data.add(new Hero("https://pahlawancenter.com/wp-content/uploads/2013/09/Kol-Sugiono-bw-253x300.jpg", "Kolonel Sugiono", "Kolonel Anumerta R. Sugiyono Mangunwiyoto, lahir di Gunung Kidul, 12 Agustus 1926.Beliau bersama Brigjend Katamso merupakan korban penculikan PKI di daerah Yogyakarta. Keduanya dikuburkan pada lubang yang sama dan mayatnya diketemukan setelah 20 hari berlalu."));
        return data;
    }
}
